---
version: "3"
services:

  prometheus:
    image: prom/prometheus:v2.19.3
    command: --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    volumes:
      - ./local/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./local/alerts/:/etc/prometheus/rules.d/

  app:
    build:
      context: .

#  pushgateway:
#    image: prom/pushgateway:v0.4.0
#    ports:
#      - 9091:9091

#   grafana:
#     image: grafana/grafana:4.6.2
#     ports:
#       - 3000:3000
#     environment:
#       - GF_SECURITY_ADMIN_PASSWORD=admin

#  alertmanager:
#    image: prom/alertmanager:v0.11.0
#    command: --config.file=/etc/alertmanager/alertmanager.yml
#    ports:
#      - 9093:9093
#    volumes:
#      - ./local/alertmanager.yml:/etc/alertmanager/alertmanager.yml

